### PR TITLE
Fix WriteKnownHost for IPv6 #1

### LINKED ISSUE #1: ipv6: missing port in address
Using `WriteKnownHost` will get an entry with ipv6:
```
mbp.local,[fe80::abc:abcd:abcd:abcd%en0] ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyN...
```

The next login fails:
```
knownhosts: /Users/lonny/.ssh/known_hosts:26: address [fe80::abc:abcd:abcd:abcd%en0]: missing port in address
```

### PR DESCRIPTION
**Pull request by lonnywong**
- Fix #1
- Fix `golangci-lint` warning:
  ```
  gosimple: S1011: should replace loop with `kkeys = append(kkeys, keyErr.Want...)`
  ```

### CODE REVIEW

File: knownhosts.go [hunk 1]
```diff
@@ -42,9 +44,7 @@ func (hkcb HostKeyCallback) HostKeys(hostWithPort string) (keys []ssh.PublicKey)
 	placeholderPubKey := &fakePublicKey{}
 	var kkeys []xknownhosts.KnownKey
 	if hkcbErr := hkcb(hostWithPort, placeholderAddr, placeholderPubKey); errors.As(hkcbErr, &keyErr) {
-		for _, knownKey := range keyErr.Want {
-			kkeys = append(kkeys, knownKey)
-		}
+		kkeys = append(kkeys, keyErr.Want...)
```
Comment (evanelias) [inline knownhosts.go:47]: Thanks for catching this. I probably mistakenly thought keyErr.Want was a map when I wrote this.

File: knownhosts_test.go [hunk 2]
```diff
@@ -151,6 +221,7 @@ func writeTestKnownHosts(t *testing.T) string {
 		"only-ed25519.example.test:22": {generagePubKeyEd25519(t)},
 		"multi.example.test:2233":      {generatePubKeyRSA(t), generatePubKeyECDSA(t), generagePubKeyEd25519(t)},
 		"192.168.1.102:2222":           {generatePubKeyECDSA(t), generagePubKeyEd25519(t)},
+		"[fe80::abc:abc:abcd:abcd]:22": {generagePubKeyEd25519(t), generatePubKeyRSA(t)},
```
Comment (evanelias) [inline knownhosts_test.go:224]: Whoops, just noticed my function name typo ("generage" instead of "generate"), I'll fix that in a commit momentarily

**Review by evanelias — APPROVED** [review]
Looks perfect, thank you for the excellent PR! I'll merge momentarily. I'll likely tag a new release next week.

**Comment by lonnywong** [comment]
@evanelias Thanks for merging quickly. I can use it without tag now.
